# Generated by Django 4.1.5 on 2023-09-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_imag_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameord', models.CharField(max_length=256)),
                ('lastnameord', models.CharField(max_length=256)),
                ('descriptionord', models.TextField()),
                ('adress', models.CharField(max_length=1000)),
                ('contact', models.CharField(max_length=1000)),
            ],
        ),
    ]
