# Generated by Django 4.1.5 on 2023-09-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='descriptionord',
            field=models.CharField(max_length=256),
        ),
    ]
