# Generated by Django 4.1.5 on 2023-09-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_order_contact_alter_order_descriptionord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='lastnameord',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.CharField(default='+', max_length=13),
        ),
        migrations.AlterField(
            model_name='order',
            name='descriptionord',
            field=models.TextField(blank=True, null=True),
        ),
    ]
