# Generated by Django 4.1.5 on 2023-09-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image2_product_image3'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us', models.CharField(blank=True, max_length=256, null=True)),
                ('prod', models.CharField(blank=True, max_length=256, null=True)),
                ('quant', models.CharField(blank=True, max_length=256, null=True)),
                ('c_t', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
