# Generated by Django 4.1.5 on 2023-09-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_image2_product_image3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categor',
        ),
    ]
