# Generated by Django 4.1.5 on 2023-09-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_categor_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
